### ISSUE TITLE
Datasets created from preexisting Tensors can be iterated at most once.

### ISSUE THREAD

**Issue by davidsoergel** [tensorflow/tfjs#1046]
The tfjs-data Dataset creation APIs assume that the underlying data (e.g., an array passed to `tf.data.array(...)` or a url passed to `tf.data.csv(...)`) can be accessed repeatedly.

However if a Dataset is created from preexisting Tensors (e.g., `tf.data.array(foo: Tensor[])`) then this assumption does not hold, because those Tensors will be disposed--at least on the first iteration through the Dataset, if not sooner.

So, we need to either:

1. Prohibit passing Tensors in.
2. Detect this situation in tf.data.array(...) and automatically apply `keep()` to the Tensors.  We should carefully document the memory-management consequences in this case, since it might not be clear to the user what's going on.
3. Accept Tensors, but automatically `.dataSync()` them.  Like 2), this has consequences / tradeoffs.
4. I think options 2 and 3 would sort of implicitly / automatically happen if you say `tf.data.array(tensors).cache()`, once we have the caching stuff hooked up (#1025, #1024).
5. ... more options I haven't thought of?

**Comment by dsmilkov** [comment]
I think the correct way is for tf.data.array(tensors) to call .clone() on each tensor internally. This increases the incref, and separates the user-owned tensors from the dataset-owned tensors. Each can dispose independently.

**Comment by dsmilkov** [comment]
Code to reproduce this issue:

```js
const a = tf.ones([2, 1]);
const b = tf.ones([2, 1]);
const ds = tf.data.array([a, b])
ds.forEach(elem => elem.print());
a.isDisposed // true, should be false.
```

**Comment by davidsoergel** [comment]
+1, that's what I meant by option 2, except that I got confused about `clone()` vs. `keep()`.  SGTM

**Comment by kangyizhang** [comment]
Even with `tf.data.array(tensors)` calling `.clone()` on each tensor internally, the created dataset still could only be iterated once, though user-owned tensors are separated. This disables multiple epoches with `model.fitDataset()`.

**Comment by dsmilkov** [comment]
Can you call clone() upon the creation of a new iterator() from an Array-backed dataset? This way multiple iterations should be fine.

**Comment by bileschi** [comment]
Is this fixed?

**Comment by kangyizhang** [comment]
Yes this is fixed.

**Comment by davidsoergel** [comment]
This is not quite fixed.

The solution at https://github.com/tensorflow/tfjs-data/blob/master/src/iterators/lazy_iterator.ts#L497 works for `Dataset<tf.Tensor>`, but not for `Dataset<tf.TensorContainer>`-- i.e., a single Tensor will be cloned, but Tensors within an array or nested structure will not.

I think we should write `tf.deepClone()` for this.  (Could be in data for now but ultimately belongs in core imho).
