### ISSUE TITLE
tfjs - speechcommands on Expo-cli app

### ISSUE THREAD

**Issue by pejoujarrar** [tensorflow/tfjs#1682]
To get help from the community, we encourage using Stack Overflow and the [`tensorflow.js`](https://stackoverflow.com/questions/tagged/tensorflow.js) tag.

#### TensorFlow.js version
"@tensorflow/tfjs": "^1.1.2"
#### Browser version
Expo-cli app
#### Describe the problem or feature request
i tried to reproduce the same functionality done in a react.js version by using tfjs/speech-commands model. But it seems that this is not working on the mobile app. first of all it was a problem of fs which does not exist on react-native, so i change it in speech-commands files to react-native-fs, no problems shown in this part after. But now, the problem is comming from ensureModelLoaded method, it throws the exception: FileReader.readAsArrayBuffed is not implemented. Is there any way to solve this, or any other method to implement speechcommand model in mobile apps? thank you.

**Comment by tafsiri** [comment]
@pejoujarrar TensorFlow.js does not currently work on react-native. We are actively working on it now, so I can let you know when we have something released that can be tested by folks in the community.

**Comment by pejoujarrar** [comment]
@tafsiri Thank you for the statement, i'm waiting for this new feature. it will be great if i can implement it.

**Comment by tafsiri** [comment]
@pejoujarrar we just released a package for this. Try it and let us know if it works, https://www.npmjs.com/package/@tensorflow/tfjs-react-native

**Comment by pejoujarrar** [comment]
@tafsiri , I would like to thank you for the release!

Unfortunately the speechCommands model from 

> @tensorflow-models/speech-commands

still can't be loaded , the method 

> recognizer.ensureModelLoaded()

is generating the following error message: 

![error](https://user-images.githubusercontent.com/49135588/64312467-ffa3e380-cfe2-11e9-9dee-542e18c0d64b.png)

This same instruction is working fine in the react.js version.

**Comment by tafsiri** [comment]
@pejoujarrar thanks, I'll look into why it doesn't load. However looking more closely, the speech-commands `listen` function` will not work as is in react native. It relies on the [web audio api](https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API) and the browser to do FFT. 

Do get around this you would need to generate the tensor for the audio manually and feed it in as mentioned here https://github.com/tensorflow/tfjs-models/tree/master/speech-commands#offline-recognition.

Just curious to know more about your use case/example, how would you get audio into your app in RN?

**Comment by pejoujarrar** [comment]
@tafsiri , Since the project is build using Expo-cli, There is no choice but using https://docs.expo.io/versions/latest/sdk/audio/ (Recording sounds).

**Comment by tafsiri** [comment]
@pejoujarrar I wasn't able to reproduce your error (I was able to load the speech commands model). Could you provide sample code that causes the issue? 

Note that you need to have `import '@tensorflow/tfjs-react-native';` and `await tf.ready();` must complete before you try to load the model.

**Comment by rthadur** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
