### ISSUE TITLE
TensorflowJS does not work on mobile Chrome browser. 

### ISSUE THREAD

**Issue by dna2github** [tensorflow/tfjs#240]
To get help from the community, check out our [Google group](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs).

#### TensorFlow.js version
https://storage.googleapis.com/tfjs-examples/mobilenet/dist/index.html

#### Browser version
Android 6.0.1
Chrome 65.0.3325.109

#### Describe the problem or feature request

TensorflowJS does not work on mobile Chrome browser.
visit https://storage.googleapis.com/tfjs-examples/mobilenet/dist/index.html on Android Chrome and wait for finishing model loading then it will use default cat.jpg to do a demo predict.

ARM Android Chrome output:

```
coyote, prairie wolf, brush wolf, Canis Iatrans 0.075
Egyptian cat 0.074
hare 0.049
wood rabbit, cottontail, conttontail rabbit 0.033
...
```

run on for example Intel MacOSX 10.12 Chrome 65.0.3328.181 output:

```
Egyptian cat	0.757
tabby, tabby cat	0.076
Siamese cat, Siamese	0.058
tiger cat	0.021
lynx, catamount	0.015
...
```
![cat.jpg](https://camo.githubusercontent.com/4eb4d75d78c4c2ef954a5f5b49a50fb1e22491ea/68747470733a2f2f73746f726167652e676f6f676c65617069732e636f6d2f74666a732d6578616d706c65732f6d6f62696c656e65742f646973742f65643231653839383230323238656331363862666466373266623132383434392e6a7067)

#### Code to reproduce the bug / link to feature request

https://storage.googleapis.com/tfjs-examples/mobilenet/dist/index.html
https://github.com/dna2github/NodeBase/tree/master/modules/tensorflowjs

direct visit from mobile Chrome and macosx Chrome to googleapis server; get problem on Android Chrome.
run a local copy on mocosx, visit from mobile Chrome and macosx Chrome; get the same problem
run a local copy on my mobile with Android 6.0.1, visit from mobile Chrome and macosx Chrome; get the same problem; 100% reproduce-able.

**Comment by nsthorat** [comment]
This should be fixed. Please reopen if you see it not working on the latest version of tfjs.

**Comment by Somil112** [comment]
I have the latest version of Tensorflow.js installed and it still doesn't work. Please help.

**Comment by Leekao** [comment]
Still having problems with mobile chrome :/

**Comment by d4em0n** [comment]
same problem!

**Comment by d4em0n** [comment]
solved this issue by changing backend to wasm

**Comment by luiskarlos** [comment]
I resolve this using https.
If you use HTTP it does not load the audio interface
