### ISSUE TITLE
Problem with COCO-SSD

### ISSUE THREAD

**Issue by vvasc** [tensorflow/tfjs#3485]
#### TensorFlow.js version
@tensorflow-models/coco-ssd": "^2.0.3",
@tensorflow/tfjs": "^2.0.1",

#### Browser version
Google Chrome
Version 83.0.4103.106 (Official Build) (64-bit)
#### Describe the problem or feature request
It seems a bug with coco-ssd version and tfjs

#### Code to reproduce the bug / link to feature request
Repository: https://github.com/vvasc/coco-ssd

```
ERROR Error: Uncaught (in promise): Error: Argument 'a' passed to 'less' must be a Tensor or TensorLike, but got 'Promise'
Error: Argument 'a' passed to 'less' must be a Tensor or TensorLike, but got 'Promise'
    at convertToTensor (tensor_util_env.js:84)
    at less_ (less.js:37)
    at Module.less (operation.js:40)
    at Module.executeOp (logical_executor.js:34)
    at operation_executor.js:63
    at engine.js:425
    at t.e.scopedRun (engine.js:436)
    at t.e.tidy (engine.js:423)
    at Module.tidy (globals.js:166)
    at operation_executor.js:63
    at resolvePromise (zone-evergreen.js:798)
    at zone-evergreen.js:705
    at rejected (tslib.es6.js:72)
    at ZoneDelegate.invoke (zone-evergreen.js:364)
    at Object.onInvoke (core.js:41654)
    at ZoneDelegate.invoke (zone-evergreen.js:363)
    at Zone.run (zone-evergreen.js:123)
    at zone-evergreen.js:857
    at ZoneDelegate.invokeTask (zone-evergreen.js:399)
    at Object.onInvokeTask (core.js:41632)
defaultErrorLogger @ core.js:6228

```

There is a problem with the coco-ssd and tfjs version, I already check the following issues https://github.com/tensorflow/tfjs/issues/1208, https://github.com/tensorflow/tfjs/issues/1190, and the problems doesn't occur in other versions. Are there incompatibilities with these versions?
I tried these packages too and I got the same problem.

```
@tensorflow-models/coco-ssd": "2.0.2",
@tensorflow/tfjs-core": "1.7.2",
```

And I already tried import using script in pure js and html, but I had the same.

**Comment by TonySpegel** [comment]
I'm also struggling with this, what combination has worked for you @vvasc ?
Mine are these:
```javascript
"@tensorflow-models/coco-ssd": "^2.0.3",
"@tensorflow/tfjs": "^2.0.1",
"@tensorflow/tfjs-backend-webgl": "^2.0.1",
```
this is a mess really, how is one supposed to use these, by guessing?

**Comment by yunho2141** [comment]
still not resolve issue?

**Comment by vvasc** [comment]
@yunho2141 Was resolved, it works now

**Comment by rfourdinier** [comment]
@vvasc may you explain how did you resolve this ? 

which versions of : 

  - "@tensorflow-models/coco-ssd"
  - "@tensorflow/tfjs"
  -  "@tensorflow/tfjs-core"
  -  "@tensorflow/tfjs-node"

are you using ?

thank you !

**Comment by rfourdinier** [comment]
Hello @pyu10055, i updated coco ssd to 2.0.1 and then last version 2.5.0  but i still have the exact same error as @vvasc did.

I am also having tfjs and backends version up to date 2.5.0 but error is still here.

Do you have any suggestion ? Thank you very much
