### ISSUE TITLE
The shape of dict['ToFloat'] provided in model.execute(dict) must be []

### ISSUE THREAD

**Issue by ghafran** [tensorflow/tfjs#4061]
When using the latest model created by automl for tensorflowjs using https://cloud.google.com/vision/automl/object-detection/docs/edge-quickstart exactly.

Has anyone else seen this issue with exporting model from automl for tensorflowjs?

When running 
`const predictions = await model.detect(img, options);`

Getting the following error:
```
util.js:109 Uncaught (in promise) Error: The shape of dict['ToFloat'] provided in model.execute(dict) must be [], but was [1,1280,1920,3]
    at Ev (util.js:109)
    at graph_executor.js:543
    at Array.forEach (<anonymous>)
    at e.t.checkInputShapeAndType (graph_executor.js:534)
    at e.<anonymous> (graph_executor.js:332)
    at u (runtime.js:45)
    at Generator._invoke (runtime.js:274)
    at Generator.forEach.e.<computed> [as next] (runtime.js:97)
    at Um (runtime.js:728)
    at o (runtime.js:728)
```

Using
```
"@tensorflow/tfjs": "^2.6.0",
"@tensorflow/tfjs-automl": "^1.0.0"
```

Full code
```
<script src="/node_modules/@tensorflow/tfjs/dist/tf.min.js"></script>
<script src="/node_modules/@tensorflow/tfjs-automl/dist/tf-automl.min.js"></script>
<img id="img" src="salad.jpg">
<script>
    async function run() {
        const model = await tf.automl.loadObjectDetection('/model/model.json');
        const img = document.getElementById('img');
        const options = { score: 0.5, iou: 0.5, topk: 20 };
        console.log(model.dictionary);
        const predictions = await model.detect(img, options);
        console.log(predictions);
        // Show the resulting object on the page.
        const pre = document.createElement('pre');
        pre.textContent = JSON.stringify(predictions, null, 2);
        document.body.append(pre);
    }
    run();
</script>
```

**Comment by peterschmiz** [comment]
I have the same issue.

**Comment by pyu10055** [comment]
@ghafran This has been fixed recently on the AutoML side, I will update this thread when the changes has been deployed.
You might need to retrain the model on the autoML side.

**Comment by peterschmiz** [comment]
Thank you very much!

**Comment by peterschmiz** [comment]
Hi @pyu10055,

I retrained my model (it tooks around 2h "wall clock" time), exported it, but I still have the error.
I assume the fix is not yet deployed.

Do you have an ETA for the deployment/fix?
(so I know when to start the re-train as it takes time and costs money 😄 )

Peter

**Comment by pyu10055** [comment]
@ghafran and @peterschmiz The fix will be deployed sometime next week.

**Comment by ghafran** [comment]
This seems to be fixed now. Its working after re-training and exporting.
