### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by pravastacaraka** [tensorflow/tfjs#4637]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 Education 20H2 64-bit
- TensorFlow.js installed from (npm or script link): npm
- TensorFlow.js version: 3.0.0
- CUDA/cuDNN version: Not using

**Describe the problem**
Previously I had a trained model from YOLOv5. Then I wanted to try running it in the browser, so I converted it to the tfjs model. However, I have a problem when inference. 

**Provide the exact sequence of commands/steps that you executed before running into the problem**
I call the element of an image, then I change it to tensor4d then I predict, but this problem always arises:
"Uncaught (in promise) TypeError: Cannot read property 'name' of undefined"

**Any other info/logs**
Uncaught (in promise) TypeError: Cannot read property 'name' of undefined
    at graph_executor.js:307
    at Array.reduce (<anonymous>)
    at GraphExecutor.executeFunctionAsync (graph_executor.js:306)
    at Module.executeOp (control_executor.js:31)
    at async Promise.all (:3000/index 0)
    at async GraphExecutor.executeWithControlFlow (graph_executor.js:351)
    at async GraphExecutor._executeAsync (graph_executor.js:285)
    at async GraphModel.executeAsync (graph_model.js:316)

**Comment by rthadur** [comment]
@pravastacaraka can you please share minimal code to reproduce the error , you can create a repo or use codepen. Thank you

**Comment by pravastacaraka** [comment]
Sorry for the late response, I've fixed this problem

**Comment by dewball345** [comment]
What did you do? i have the same problem.

**Comment by pravastacaraka** [comment]
@dewball345 Unfortunately there is no way to fix this yet. As we know on PR https://github.com/ultralytics/yolov5/pull/1127 using ops `tf.image.combined_non_max_suppression()` which apparently is not supported by TensorFlow.js. So we have to convert YOLOv5 model `*.pt` to TensorFlow.js model without using `--tf-nms` argument and apply NMS manually in our website program.

**Comment by dewball345** [comment]
> Sorry for the late response, I've fixed this problem

Okay, so why did you put this then? also, I converted from pytorch to onnx to tensorflow .pb then to tensorflowjs with tensorflow_converter. Was there anything else that you did?

**Comment by dewball345** [comment]
I will try later using this PR as well, though I think there may be something wrong with my input. Can i see your tensorflow.js inference code? thanks!

**Comment by dewball345** [comment]
Okay, so i was able to conduct inference in tensorflow.js and am currently working on a non-max suppression algorithm. What i did previously is that I converted pytorch -> onnx -> tensorflow saved model -> tensorflow.js. In the last step, there may have been some kind of conversion error. I suggest you use @zldrobit's tensorflow branch of this repo. You can find the link at https://github.com/zldrobit/yolov5/.

**Comment by pravastacaraka** [comment]
@dewball345 Have you finished the algorithm of non-max suppression?

**Comment by dewball345** [comment]
No, not yet. You know, it's. Actually quite simple(just turn the non max
suppression function in utils.general to js)

**Comment by dewball345** [comment]
Okay, you can expect it soon; i'm probably going to make a repo with it

**Comment by pravastacaraka** [comment]
@dewball345 I really appreciate it. Awaited the good news!

**Comment by dewball345** [comment]
@pravastacaraka Okay, i implemented the nms as well as some pre/post processing, and you can view it [here](https://github.com/dewball345/ear.js)

**Comment by nimishdesai1989** [comment]
hello @pravastacaraka : i am still getting this error on using the ssd_mobilenet v2 model.

![22399021-BB51-4439-A318-AA0C18A7CE58](https://user-images.githubusercontent.com/67813597/130784452-eaff2d6d-ef7f-4aeb-bb82-4ac11019d443.jpeg)

I used the repo and training from tensorflow blog below.
https://blog.tensorflow.org/2021/01/custom-object-detection-in-browser.html

Is there any help you all can offer. I am bit new to this object detection and I think I am stuck.
