### ISSUE TITLE
Error: TensorList shape mismatch: Shapes -1 and 3 must match

### ISSUE THREAD

**Issue by VernengoSimone** [tensorflow/tfjs#4641]
**System information**
- I'm trying to convert a TF Object Detection model to SavedModel and then TF.js without any customization
- I'm working on Colab to export the model and I load the converted model on Chrome.
- Chrome version 88.0.4324.146 (Official Build) (64-bit)
- TensorFlow.js installed from yarn
- tfjs-core: ^3.0.0
- tfjs-converter: ^3.0.0
- TF 2.4.1
- Python 3.6.9

I'm currently trying to convert to TF.js one of the Object Detection models from the TF2 OD ZOO, in particular SSD MobileNet V2 FPNLite 320x320.

When I convert the model pre-existing SavedModel to TF.js from the saved_model folder I'm able to import it in my browser and launch it through executeAsync(). If I keep the original pipeline.config and try to create another SavedModel from the provided checkpoint using this line

```
python exporter_main_v2.py --input_type image_tensor \
    --pipeline_config_path ./pre-trained-models/ssd320/pipeline.config \
    --trained_checkpoint_dir ./pre-trained-models/ssd320/checkpoint_0 \
    --output_directory ./pre-trained-models/ssd320/exported_model
```

after I convert it to TF.js with the following line

```
tensorflowjs_converter \
    --input_format=tf_saved_model \
    --saved_model_tags=serve \
    ./pre-trained-models/ssd320/path-to-savedmodel-folder \
    ./pre-trained-models/tfjs_test
```

I encounter the following error when I try to launch the inference on my browser

```
util_base.js?a6b2:141 Uncaught (in promise) Error: TensorList shape mismatch:  Shapes -1 and 3 must match
    at Module.assert (util_base.js?a6b2:141)
    at assertShapesMatchAllowUndefinedSize (tensor_utils.js?74aa:24)
    at TensorList.setItem (tensor_list.js?41f7:182)
    at Module.executeOp (control_executor.js?de9e:188)
    at eval (operation_executor.js?be85:52)
    at executeOp (operation_executor.js?be85:94)
    at GraphExecutor.processStack (graph_executor.js?33ef:390)
    at GraphExecutor.executeWithControlFlow (graph_executor.js?33ef:350)
    at async GraphExecutor._executeAsync (graph_executor.js?33ef:285)
    at async GraphModel.executeAsync (graph_model.js?9724:316)
```

I tried with SSD MobileNet v2 320x320 (no FPN here) and the outcome is the same. I'm starting to think that it may be connected to the use of exporter_main_v2.py but I wouldn't know how to convert the model without it.

Could you please help me figure out something more about the cause of this issue?

**Comment by luke-iqt** [comment]
I am having the exact same problem. I am trying to use a model I trained using the TF2 Obj Detection API. I did transfer learning on top of the MobileNet V2 SSD model, exported to saved graph using exporter_main_v2.py. I used the tensorflowjs_converter.

I get the same message from just trying to feed in a Zero Tensor, made with this code:
````
    const zeroTensor = tf.zeros([1, 300, 300, 3], 'int32');
    // Warmup the model.
    const result = await this.model.executeAsync(zeroTensor) as tf.Tensor[];
````

Is there a better way to run a Custom TF2 Object Detection model in TFjs?

**Comment by umitkacar** [comment]
I tried too many times the problem persists. How am I going to do this? Can you help me?

**Comment by nirchetrit** [comment]
I have the same exact error when training the model using the object detection API. all works fine right to the point where I convert the model to TFJS.
after loading an image I got the error:
TensorList shape mismatch: Shapes -1 and 3 must match

**Comment by umitkacar** [comment]
I've been working for a week. This error appears to be from open source applications that were not in previous versions. I even tried from old models. They are working. But the one I just created doesn't work.

**Comment by lina128** [comment]
This issue is resolved in https://github.com/tensorflow/tfjs/pull/4657 , which is released in 3.1.0, please try the latest version.

**Comment by VernengoSimone** [comment]
I tried the latest version
`
$ yarn list --depth 0
yarn list v1.22.5

├─ @tensorflow-models/coco-ssd@2.2.1
├─ @tensorflow/tfjs-backend-cpu@3.1.0
├─ @tensorflow/tfjs-backend-webgl@3.1.0
├─ @tensorflow/tfjs-converter@3.1.0
├─ @tensorflow/tfjs-core@3.1.0
├─ @tensorflow/tfjs-data@3.1.0
├─ @tensorflow/tfjs-layers@3.1.0
├─ @tensorflow/tfjs@3.1.0
├─ test-ssd@1.0.0

`

**Comment by VernengoSimone** [comment]
I checked my tensorflow version, still have this issue

`
yarn list v1.22.5

├─ @tensorflow/tfjs-backend-cpu@3.1.0
├─ @tensorflow/tfjs-backend-webgl@3.1.0
├─ @tensorflow/tfjs-converter@3.1.0
├─ @tensorflow/tfjs-core@3.1.0
├─ @tensorflow/tfjs-data@3.1.0
├─ @tensorflow/tfjs-layers@3.1.0
├─ @tensorflow/tfjs@3.1.0

Done in 2.02s.
`

**Comment by nikhilparmar** [comment]
> This issue is resolved in #4657 , which is released in 3.1.0, please try the latest version.

I am still having the issue despite having the version 3.1.0. 
Please help.
Thanks

**Comment by lina128** [comment]
@nikhilparmar Can you share your code and model or steps to produce? Thank you.

**Comment by pyu10055** [comment]
I believe this issue has been fixed, please try out tfjs version > 3.5.0

**Comment by avinashnair02** [comment]
"TensorList shape mismatch:  Shapes -1 and 3 must match"


model link  https://appptest12.herokuapp.com/model.json

**Comment by lina128** [comment]
Please tfjs-node@3.13.0 as well.

**Comment by avinashnair02** [comment]
![image](https://user-images.githubusercontent.com/48132861/149622701-aa846696-ddb3-49ec-be09-b77e89fc365b.png)

**Comment by avinashnair02** [comment]
> Please tfjs-node@3.13.0 as well.

I did  but issues  was still not resolved!

**Comment by rthadur** [comment]
related issues https://github.com/tensorflow/tfjs/issues/4684

**Comment by gaikwadrahul8** [comment]
Hi, @VernengoSimone 

Apologize for the delayed response and we're re-visiting our older issues and checking whether those issues got resolved or not as of now so May I know are you still looking for the solution or your issue got resolved ? please also check this duplicate issue https://github.com/tensorflow/tfjs/issues/4684

If issue still persists after trying with latest version of TFJs please let us know with error log and code snippet to replicate the same issue from our end ?

Could you please confirm if this issue is resolved for you ? Please feel free to close the issue if it is resolved ? Thank you!
