### ISSUE TITLE
tensorflowjs_converter Object Detection API Model failed: dtype bool not supported

### ISSUE THREAD

**Issue by 116050423** [tensorflow/tfjs#550]
To get help from the community, check out our [Google group](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs).

#### TensorFlow.js version
tensorflowjs_converter --version
Using TensorFlow backend.

tensorflowjs 0.5.4

Dependency versions:
  keras 2.1.6
  tensorflow 1.9.0

#### Browser version
N/A
#### Describe the problem or feature request
@pyu10055 I followed your converter related PRs and much thanks for your contribution on supporting all kinds of op.
Several weeks ago I meet the unsupported op issue when converting Object Detection models.
I noticed today you release 0.5.4, I install by pip and try to convert some Object Detection models.
Now unsupported op issues gone, but I still cannot successfully convert OD related models as below:
ssdlite_mobilenet_v2_coco_2018_05_09
ssd_mobilenet_v1_coco_2018_01_28
Would you please help?

#### Code to reproduce the bug / link to feature request
tensorflowjs_converter \
  --input_format=tf_saved_model \
  --output_node_names='detection_boxes,detection_scores,num_detections,detection_classes' \
  --saved_model_tags=serve \
  ./ssdlite_mobilenet_v2_coco_2018_05_09/saved_model \
  ./web_model
Using TensorFlow backend.
2018-07-26 17:07:36.002977: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-07-26 17:07:43.454014: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:366] Optimization results for grappler item: graph_to_optimize
2018-07-26 17:07:43.454040: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:368]   debug_stripper: Graph size after: 7696 nodes (0), 11702 edges (0), time = 26.441ms.
2018-07-26 17:07:43.454046: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:368]   model_pruner: Graph size after: 7205 nodes (-491), 11211 edges (-491), time = 117.801ms.
2018-07-26 17:07:43.454051: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:368]   constant folding: Graph size after: 5618 nodes (-1587), 9396 edges (-1815), time = 772.638ms.
2018-07-26 17:07:43.454056: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:368]   arithmetic_optimizer: Graph size after: 4074 nodes (-1544), 7871 edges (-1525), time = 262.573ms.
2018-07-26 17:07:43.454061: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:368]   dependency_optimizer: Graph size after: 4036 nodes (-38), 7799 edges (-72), time = 128.838ms.
2018-07-26 17:07:43.454112: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:368]   model_pruner: Graph size after: 4036 nodes (0), 7799 edges (0), time = 38.209ms.
2018-07-26 17:07:43.454123: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:368]   constant folding: Graph size after: 4036 nodes (0), 7799 edges (0), time = 345.479ms.
2018-07-26 17:07:43.454129: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:368]   arithmetic_optimizer: Graph size after: 4034 nodes (-2), 7795 edges (-4), time = 190.297ms.
2018-07-26 17:07:43.454134: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:368]   dependency_optimizer: Graph size after: 4034 nodes (0), 7795 edges (0), time = 120.982ms.
2018-07-26 17:07:43.454138: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:368]   debug_stripper: Graph size after: 4034 nodes (0), 7795 edges (0), time = 20.877ms.
2018-07-26 17:07:43.454143: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:368]   model_pruner: Graph size after: 4034 nodes (0), 7795 edges (0), time = 36.301ms.
2018-07-26 17:07:43.454186: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:368]   constant folding: Graph size after: 4034 nodes (0), 7795 edges (0), time = 206.739ms.
2018-07-26 17:07:43.454197: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:368]   arithmetic_optimizer: Graph size after: 4034 nodes (0), 7795 edges (0), time = 183.145ms.
2018-07-26 17:07:43.454202: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:368]   dependency_optimizer: Graph size after: 4034 nodes (0), 7795 edges (0), time = 117.976ms.
2018-07-26 17:07:43.454207: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:368]   model_pruner: Graph size after: 4034 nodes (0), 7795 edges (0), time = 38.166ms.
2018-07-26 17:07:43.454212: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:368]   constant folding: Graph size after: 4034 nodes (0), 7795 edges (0), time = 200.511ms.
2018-07-26 17:07:43.454217: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:368]   arithmetic_optimizer: Graph size after: 4034 nodes (0), 7795 edges (0), time = 183.155ms.
2018-07-26 17:07:43.454422: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:368]   dependency_optimizer: Graph size after: 4034 nodes (0), 7795 edges (0), time = 123.046ms.
Writing weight file ./web_model/tensorflowjs_model.pb...
Traceback (most recent call last):
  File "/usr/local/bin/tensorflowjs_converter", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/tensorflowjs/converters/converter.py", line 242, in main
    strip_debug_ops=FLAGS.strip_debug_ops)
  File "/usr/local/lib/python3.6/site-packages/tensorflowjs/converters/tf_saved_model_conversion.py", line 281, in convert_tf_saved_model
    optimize_graph(graph, output_graph, quantization_dtype, strip_debug_ops)
  File "/usr/local/lib/python3.6/site-packages/tensorflowjs/converters/tf_saved_model_conversion.py", line 121, in optimize_graph
    extract_weights(optimized_graph, output_graph, quantization_dtype)
  File "/usr/local/lib/python3.6/site-packages/tensorflowjs/converters/tf_saved_model_conversion.py", line 164, in extract_weights
    [const_manifest], path, quantization_dtype=quantization_dtype)
  File "/usr/local/lib/python3.6/site-packages/tensorflowjs/write_weights.py", line 115, in write_weights
    group_bytes, total_bytes, _ = _stack_group_bytes(group)
  File "/usr/local/lib/python3.6/site-packages/tensorflowjs/write_weights.py", line 192, in _stack_group_bytes
    _assert_valid_weight_entry(entry)
  File "/usr/local/lib/python3.6/site-packages/tensorflowjs/write_weights.py", line 292, in _assert_valid_weight_entry
    data.dtype.name + ' not supported.')
ValueError: Error dumping weight Postprocessor/BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/cond/Greater, dtype bool not supported.

**Comment by 116050423** [comment]
You can download the models here:
https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md

**Comment by bileschi** [comment]
@pyu10055 do you see some avenue for debugging here?

**Comment by bileschi** [comment]
It looks like the dtype `bool` should be supported, based on line 24:
```
_OUTPUT_DTYPES = [np.float32, np.int32, np.uint8, np.uint16, np.bool]
```
Is the weight somehow a raw bool, instead of an np.array of bools?

**Comment by bileschi** [comment]
FYI, this recent PR in converter might be relevant:
https://github.com/tensorflow/tfjs-converter/pull/186

**Comment by 116050423** [comment]
Update.
I download the source code and build the latest converter, seems can be converted.
But when I load the model using JavaScript, I meet below error, still dtype bool issue.
The reproduce procedure is simple.
Converte ssd_mobilenet_v1_coco_2018_01_28 and then load it.
I supplied the download url above.

tf-core.esm.js:227 Uncaught (in promise) Error: Weight Postprocessor/BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/cond/Greater has unknown dtype bool.
    at eval (tf-core.esm.js:227)
    at Array.forEach (<anonymous>)
    at eval (tf-core.esm.js:227)
    at Array.forEach (<anonymous>)
    at Object.eval (tf-core.esm.js:227)
    at eval (tf-core.esm.js:227)
    at Object.eval [as next] (tf-core.esm.js:227)
    at i (tf-core.esm.js:227)

**Comment by dsmilkov** [comment]
The bool support on the `tfjs-converter` side was added in https://github.com/tensorflow/tfjs-converter/pull/186 (released in `tfjs-converter 0.5.5`), while the support on the `tfjs-core` side was added in https://github.com/tensorflow/tfjs-core/pull/1190 (released in `tfjs-core 0.12.8`).

I'll close this issue but let me know if this is still relevant once you try with those versions.

**Comment by jantonysolstice** [comment]
I'm having the same problem on 0.5.6 and 0.12.9, ```to-object.js:6 Uncaught (in promise) Error: Weight Postprocessor/BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/cond_3/cond/switch_f has unknown dtype bool```

**Comment by dsmilkov** [comment]
I just tried it and not getting any error. Make sure you are using the 0.5.6 of tfjs_converter. The package lives on [pypi](https://pypi.org/project/tensorflowjs/).

To see which version you have run `tensorflowjs_converter --version`.
To upgrade, run `pip install tensorflowjs --upgrade`

**Comment by dsmilkov** [comment]
Hi! Apologies for the premature answer. I just realized that while the fixes are in, we haven't yet released a new version of tfjs that contains those fixes. We'll release a new patch version most likely tomorrow.

**Comment by jantonysolstice** [comment]
Is the issue with tfjs or the converter? Is it fixed now? Thanks by the way

**Comment by raj-sivakumar** [comment]
> I'm having the same problem on 0.5.6 and 0.12.9, `to-object.js:6 Uncaught (in promise) Error: Weight Postprocessor/BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/cond_3/cond/switch_f has unknown dtype bool`
> With the ssd_mobilenet_v1 coco model

I'm having the same error currently. Have tried both those versions and the latest versions of tensorflowjs(python) and tfjs(JS packages).

**Comment by dsmilkov** [comment]
cc @pyu10055 Users are still seeing the unknown dtype `bool` in the converter even though that got added a few versions again.

**Comment by pyu10055** [comment]
@raj-sivakumar  0.5.6 and 0.12.9 are rather old, can you try the latest versions (0.7.x and 0.14.x)? thanks.

**Comment by raj-sivakumar** [comment]
@pyu10055 Thank you for your response. I had initially started with the latest versions, which is when I switched to the older versions mentioned above per the recommendation of this thread.
