### ISSUE TITLE
gradient function not found for Einsum

### ISSUE THREAD

**Issue by santiontanon** [tensorflow/tfjs#5690]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS 11.4
- TensorFlow.js version (use command below): tfjs@3.9.0
- Browser version: Google Chrome Version 94.0.4606.71
- Tensorflow.js Converter Version: ???

**Describe the current behavior**
Upon using the "tf.einsum" method in a custom layer, I get the following message :

tape.js:152 Uncaught (in promise) Error: Cannot compute gradient: gradient function not found for Einsum.
    at a (tape.js:152)
    at tape.js:136
    at engine.js:1120
    at engine.js:467
    at e.t.scopedRun (engine.js:478)
    at e.t.tidy (engine.js:465)
    at e.t.gradients (engine.js:1115)
    at GT (gradients.js:308)
    at t.n.computeGradients (optimizer.js:111)
    at t.n.minimize (optimizer.js:61)

**Describe the expected behavior**

I see einsum was added recently, so maybe gradients are still not supported. But it would be great to be abl 

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/CodePen/any notebook.

[My current project is fairly big to share, but happy to produce a small snippet that will result in this error, if this was not expected]

**Comment by gaikwadrahul8** [comment]
Hi, @santiontanon 

Apologize for the delayed response and we are re-visiting our older feature requests and checking whether those feature requests implemented or not as of now and I see we have implemented [tf.einsum](https://js.tensorflow.org/api/4.4.0/#einsum) so I'm not sure whether gradient is supporting or not at the moment so Could you please give it try with latest version of `@tensorflow/tfjs@4.5.0 `and check whether your issue is resolving or not ? and below are the limitations of `tf.einsum `

If issue still persists please let us know ? Thank you!

```
This implementation of einsum has the following limitations:

Does not support >2 input tensors.
Does not support duplicate axes for any given input tensor. E.g., equation 'ii->' is not supported.
The ... notation is not supported.
```

**Comment by JulienVig** [comment]
Hi @gaikwadrahul8, the issue is still present for me on 4.20.0
```js
// a has shape [ 16, 16, 48 ] and b has shape [ 50257, 48 ] 
tf.einsum('ijk,bk->ijb', a, b)
```
