### ISSUE TITLE
tfjs-models: make pose-detection deno compatible

### ISSUE THREAD

**Issue by andykais** [tensorflow/tfjs#6746]
I am attempting to get tensorflowjs running within deno. A basic script like the following will work:
```ts
import * as tf from 'https://cdn.skypack.dev/@tensorflow/tfjs'
import 'https://cdn.skypack.dev/@tensorflow/tfjs-backend-webgpu'

// initialize tensorflow
await tf.setBackend('webgpu')
await tf.ready()
const tensor = tf.tensor1d([0])
tensor.print()
```
```bash
deno run --allow-write --allow-read --unstable mod.ts
```

I can _also_ load up a model, specifically over http, using the `file://` protocol actually still triggers a fetch, which deno fails on.
```ts
import * as tf from 'https://cdn.skypack.dev/@tensorflow/tfjs'
import 'https://cdn.skypack.dev/@tensorflow/tfjs-backend-webgpu'

// initialize tensorflow
await tf.setBackend('webgpu')
await tf.ready()

const model = await tf.loadGraphModel(`https://storage.googleapis.com/tfhub-tfjs-modules/google/tfjs-model/movenet/singlepose/lightning/4/model.json`, {
  fetchFunc: fetch
})
```

However, I would like to be able to reuse some of the code in tfjs-models, since there is a decent amount of code that makes the output from the models useful. This is the following code snippet I want to get working:
```ts
import * as tf from 'https://cdn.skypack.dev/@tensorflow/tfjs'
import 'https://cdn.skypack.dev/@tensorflow/tfjs-backend-webgpu'
import * as poseDetection from 'https://cdn.skypack.dev/@tensorflow-models/pose-detection';

// initialize tensorflow
await tf.setBackend('webgpu')
await tf.ready()

const detectorConfig = {
  modelType: poseDetection.movenet.modelType.SINGLEPOSE_LIGHTNING,
}
const detector = await poseDetection.createDetector(poseDetection.SupportedModels.MoveNet, detectorConfig)
```

**System information** MacOS M1
- TensorFlow.js version (you are using): `v3.14.0`
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
tfjs throws an error
```
error: Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'fetch')
      this.fetch = env().platform.fetch;
```

**Will this change the current api? How?**
yes, adding a third option to the `createDetector` method. Example:
```ts
const detector = await poseDetection.createDetector(
  poseDetection.SupportedModels.MoveNet,
  detectorConfig,
  { fetchFunc: fetch }
)
```

**Who will benefit with this feature?**
anyone porting tensoflowjs to deno trying to use the pose detection 

**Any Other info.**
`deno --version`
```
deno 1.24.1 (release, aarch64-apple-darwin)
v8 10.4.132.20
typescript 4.7.4
```

**Comment by andykais** [comment]
that prints

```
false
false
```

I may be able to get away with the browser platform if I can somehow force that. Deno implements most browser apis. Is it possible to manually force the platform? If not, can you at least point me to where it is detected?

**Comment by andykais** [comment]
yeah so looking at the browser_platform.ts file, this should function fine in deno, if we can force it https://github.com/tensorflow/tfjs/blob/master/tfjs-core/src/platforms/platform_browser.ts. IndexedDB is not implemented in deno, but that appears to be an optional requirement for the browser platform. Still havent found where we detect the platform. I imagine the indexedDB is used to cache the models?

**Comment by andykais** [comment]
Ok I see. Here it is https://github.com/tensorflow/tfjs/blob/a1e5aeabc24271ac4f9eefb434b2e6076367693a/tfjs-core/src/device_util.ts#L60. It is because of `window.document != null`. In deno, `window.document` is `undefined`. 

So actually, I think this could be possibly be solved by simply removing the `window.document` check entirely. A quick scan of the tfjs repo shows that the only reference to `window.document` is in this `isBrowser()` function so it feels like it might be unnecessary (tfjs isnt interacting with the document tree in any way).

**Comment by pyu10055** [comment]
I think it is possible to make deno looks like browser, but conceptually it is not a browser.
It might have more efficient way of doing things relative to browser.

If you want to hack the API to testing it out, it might be easier to inject a mock `document` object to `window` variable.

**Comment by andykais** [comment]
I guess what I am describing is "duck typing", which to a degree, is what you already are checking. You have a check that is essentially: if it looks like a browser, treat it like a browser. All I am suggesting is to not check browser apis that your library does not use.

Alright testing it out, it doesnt actually appear to set `IS_BROWSER` to true.
```ts
;(window as any).document = {} // polyfill for browser detection
import * as tf from 'https://cdn.skypack.dev/@tensorflow/tfjs'
import 'https://cdn.skypack.dev/@tensorflow/tfjs-backend-webgpu'
import * as poseDetection from 'https://cdn.skypack.dev/@tensorflow-models/pose-detection';


// initialize tensorflow
await tf.setBackend('webgpu')
await tf.ready()

console.log('isBrowser:', tf.device_util.isBrowser())
console.log('IS_BROWSER:', tf.env().getBool('IS_BROWSER'));
```
this logs
```
isBrowser: true
IS_BROWSER: false
```

either `window` has a different scope inside these modules, or I am reading the code wrong. I can eventually get the tfjs-models repo to build in deno,  but its going to require building a import_map.json for module resolution, or bundling for the browser. Doable, but its just going to take time to debug

Actually, this doesnt seem to work either.
```ts
;(window as any).document = {} // polyfill for browser detection
import * as tf from 'https://cdn.skypack.dev/@tensorflow/tfjs'
tf.env().set('IS_BROWSER', true)
import 'https://cdn.skypack.dev/@tensorflow/tfjs-backend-webgpu'
import * as poseDetection from 'https://cdn.skypack.dev/@tensorflow-models/pose-detection';


// initialize tensorflow
await tf.setBackend('webgpu')
await tf.ready()

console.log('isBrowser:', tf.device_util.isBrowser())
console.log('IS_BROWSER:', tf.env().getBool('IS_BROWSER'));

const detectorConfig = {
  modelType: poseDetection.movenet.modelType.SINGLEPOSE_LIGHTNING,
}
const detector = await poseDetection.createDetector(poseDetection.SupportedModels.MoveNet, detectorConfig)
```
it still fails with 
```
error: Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'fetch')
      this.fetch = env().platform.fetch;
```
I suppose theres more debugging to do

**Comment by haoyunfeix** [comment]
The reason might be the env `IS_BROWSER` set to TURE after [register platforms](https://github.com/tensorflow/tfjs/blob/master/tfjs-core/src/base_side_effects.ts#L27), miss the timing of creating browser platforms.
One hack way to manually set browser platform as following code may solve this simple, since deno has supported LocalStorage IOHandler.
```javascript
;(window as any).document = {} // polyfill for browser detection
import * as tf from 'https://cdn.skypack.dev/@tensorflow/tfjs'
tf.env().set('IS_BROWSER', true)
import {PlatformBrowser} from 'https://cdn.skypack.dev/@tensorflow/tfjs-core/dist/platforms/platform_browser'
tf.env().setPlatform('browser', new PlatformBrowser());
import 'https://cdn.skypack.dev/@tensorflow/tfjs-backend-webgpu'
import * as poseDetection from 'https://cdn.skypack.dev/@tensorflow-models/pose-detection';


// initialize tensorflow
await tf.setBackend('webgpu')
await tf.ready()

console.log('isBrowser:', tf.device_util.isBrowser())
console.log('IS_BROWSER:', tf.env().getBool('IS_BROWSER'));

const detectorConfig = {
  modelType: poseDetection.movenet.modelType.SINGLEPOSE_LIGHTNING,
}
const detector = await poseDetection.createDetector(poseDetection.SupportedModels.MoveNet, detectorConfig)

```

**Comment by andykais** [comment]
@haoyunfeix I tried out your example and was able to at least get tensorflowjs to register the platform as deno. Going one step further to estimate a pose however, yields this error:
```ts
import * as jpegts from "https://deno.land/x/jpegts@1.1/mod.ts";
;(window as any).document = {} // polyfill for browser detection
import * as tf from 'https://cdn.skypack.dev/@tensorflow/tfjs'
tf.env().set('IS_BROWSER', true)
import {PlatformBrowser} from 'https://cdn.skypack.dev/@tensorflow/tfjs-core/dist/platforms/platform_browser'
tf.env().setPlatform('browser', new PlatformBrowser());
import 'https://cdn.skypack.dev/@tensorflow/tfjs-backend-webgpu'
import * as poseDetection from 'https://cdn.skypack.dev/@tensorflow-models/pose-detection';


// initialize tensorflow
await tf.setBackend('webgpu')
await tf.ready()

console.log('isBrowser:', tf.device_util.isBrowser())
console.log('IS_BROWSER:', tf.env().getBool('IS_BROWSER'));

const detectorConfig = {
  modelType: poseDetection.movenet.modelType.MULTIPOSE_LIGHTNING,
}
const detector = await poseDetection.createDetector(poseDetection.SupportedModels.MoveNet, detectorConfig)

const file = await Deno.readFile('./sample.jpg')
const image = await jpegts.decode(file)
const poses = await detector.estimatePoses(image);
console.log(poses)
```

```
This device doesn't support timestamp-query extension. Start Chrome browser with flag --disable-dawn-features=disallow_unsafe_apis then try again. Or zero will shown for the kernel time when profiling mode isenabled. Using performance.now is not workable for webgpu sinceit doesn't support synchronously to read data from GPU.
isBrowser: true
IS_BROWSER: true
error: Uncaught (in promise) Error: Kernel 'Reciprocal' not registered for backend 'webgpu'
      throw new Error(`Kernel '${kernelName}' not registered for backend '${this.backendName}'`);
            ^
    at Engine.runKernel (https://cdn.skypack.dev/-/@tensorflow/tfjs-core@v3.19.0-amlY93jd2dBqG3L2cxZ0/dist=es2019,mode=imports/optimized/@tensorflow/tfjs-core.js:2535:13)
    at reciprocal_ (https://cdn.skypack.dev/-/@tensorflow/tfjs-core@v3.14.0-1sdjJhmH325m7a84aLb9/dist=es2019,mode=imports/unoptimized/dist/ops/reciprocal.js:24:17)
    at reciprocal__op (https://cdn.skypack.dev/-/@tensorflow/tfjs-core@v3.14.0-1sdjJhmH325m7a84aLb9/dist=es2019,mode=imports/unoptimized/dist/ops/operation.js:34:22)
    at executeOp$1 (https://cdn.skypack.dev/-/@tensorflow/tfjs-converter@v3.14.0-YN7NizmfUVcf8pFaMZEp/dist=es2019,mode=imports/optimized/@tensorflow/tfjs-converter.js:8571:15)
    at https://cdn.skypack.dev/-/@tensorflow/tfjs-converter@v3.14.0-YN7NizmfUVcf8pFaMZEp/dist=es2019,mode=imports/optimized/@tensorflow/tfjs-converter.js:10502:27
    at https://cdn.skypack.dev/-/@tensorflow/tfjs-core@v3.19.0-amlY93jd2dBqG3L2cxZ0/dist=es2019,mode=imports/optimized/@tensorflow/tfjs-core.js:2490:16
    at Engine.scopedRun (https://cdn.skypack.dev/-/@tensorflow/tfjs-core@v3.19.0-amlY93jd2dBqG3L2cxZ0/dist=es2019,mode=imports/optimized/@tensorflow/tfjs-core.js:2500:19)
    at Engine.tidy (https://cdn.skypack.dev/-/@tensorflow/tfjs-core@v3.19.0-amlY93jd2dBqG3L2cxZ0/dist=es2019,mode=imports/optimized/@tensorflow/tfjs-core.js:2489:17)
    at tidy (https://cdn.skypack.dev/-/@tensorflow/tfjs-core@v3.14.0-1sdjJhmH325m7a84aLb9/dist=es2019,mode=imports/optimized/@tensorflow/tfjs-core.js:7781:17)
    at https://cdn.skypack.dev/-/@tensorflow/tfjs-converter@v3.14.0-YN7NizmfUVcf8pFaMZEp/dist=es2019,mode=imports/optimized/@tensorflow/tfjs-converter.js:10502:16
```

removing the webgpu import and the line `await tf.setBackend('webgpu')` does output a pose estimation, though its using the cpu backend

**Comment by qjia7** [comment]
> error: Uncaught (in promise) Error: Kernel 'Reciprocal' not registered for backend 'webgpu'
>       throw new Error(`Kernel '${kernelName}' not registered for backend '${this.backendName}'`);

This [op](https://github.com/tensorflow/tfjs/pull/6743) was added two weeks ago. Please try the latest webgpu (0.0.1-alpha.13) npm package, or you can build your own from the source. Thanks.

**Comment by haoyunfeix** [comment]
@andykais, @qjia7 is right, please use latest code, I tried your pasted code with `deno cache --reload mod.ts` to get webgpu and tfjs updated.
But got error as below:
```
Initialization of backend webgpu failed
TypeError: device.features.has is not a function
    at new WebGPUBackend (https://cdn.skypack.dev/-/@tensorflow/tfjs-backend-webgpu@v0.0.1-alpha.13-81rwa8j159gasYKEb1qh/dist=es2019,mode=imports/optimized/@tensorflow/tfjs-backend-webgpu.js:1076:45)
    at Object.factory (https://cdn.skypack.dev/-/@tensorflow/tfjs-backend-webgpu@v0.0.1-alpha.13-81rwa8j159gasYKEb1qh/dist=es2019,mode=imports/optimized/@tensorflow/tfjs-backend-webgpu.js:1624:12)
    at async Engine.setBackend (https://cdn.skypack.dev/-/@tensorflow/tfjs-core@v3.20.0-bzrrCCIwo5CExYFUBlDy/dist=es2019,mode=imports/optimized/@tensorflow/tfjs-core.js:2360:34)
    at async file:///workspace/project/tfjswebgpu/tfjs-yunfei/6746/mod2.ts:14:1
WARNING: lavapipe is not a conformant vulkan implementation, testing use only.
```
I thought it maybe a WebGPU implement bug in deno. Due to [WebGPU spec](https://www.w3.org/TR/webgpu/#gpu-supportedfeatures) and webidl spec, `device.features` is a [setlike](https://webidl.spec.whatwg.org/#dfn-set-entries) Object and should includes `has` method, but there is not.

I've submitted a bug to deno upstream https://github.com/denoland/deno/issues/15702

**Comment by andykais** [comment]
thanks @haoyunfeix, I did a `--reload` and see the same error as you now. Curious though that `await tf.setBackend('webgpu') logs an exception, but does not throw it

**Comment by haoyunfeix** [comment]
It's by design I think, if your `throw it` means throw exception and abort application, TFJS prefers to tell you hey there is something wrong in setting up webgpu let's keep default cpu backend and make your app running.
`tf.setBackend(): Promise<boolean>` in another way, you can check API return value in your app design to determine throw exception or not.

Although in our case, the exception happened in `import 'https://cdn.skypack.dev/@tensorflow/tfjs-backend-webgpu'`, exactly in `registerBackend(): boolean`, same as above TFJS warns you and returns result computing on default CPU backend.

**Comment by vicary** [comment]
I built Deno from source using my fork in PR https://github.com/denoland/deno/pull/15853 and the backend check passes.

I can do `await tf.ready();` and `tf.getBackend();` gives me `"webgpu"`.

But when I tried to decode the model outputs via `await tensor.array();`, it throws the following error:

```
TypeError: Cannot read properties of undefined (reading 'backend')
```

<details>
<summary>Full stack trace (click to open)</summary>

```
error: Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'backend')
    const srcBackend = info.backend;
                            ^
    at Engine.moveData (https://cdn.skypack.dev/-/@tensorflow/tfjs-core@v3.20.0-bzrrCCIwo5CExYFUBlDy/dist=es2019,mode=imports/optimized/@tensorflow/tfjs-core.js:2463:29)
    at DataStorage.get (https://cdn.skypack.dev/-/@tensorflow/tfjs-core@v3.20.0-bzrrCCIwo5CExYFUBlDy/dist=es2019,mode=imports/optimized/@tensorflow/tfjs-core.js:33:22)
    at WebGPUBackend.convertAndCacheOnCPU (https://cdn.skypack.dev/-/@tensorflow/tfjs-backend-webgpu@v0.0.1-alpha.13-81rwa8j159gasYKEb1qh/dist=es2019,mode=imports/optimized/@tensorflow/tfjs-backend-webgpu.js:1240:39)
    at WebGPUBackend.read (https://cdn.skypack.dev/-/@tensorflow/tfjs-backend-webgpu@v0.0.1-alpha.13-81rwa8j159gasYKEb1qh/dist=es2019,mode=imports/optimized/@tensorflow/tfjs-backend-webgpu.js:1276:10)
    at async Tensor.array (https://cdn.skypack.dev/-/@tensorflow/tfjs-core@v3.20.0-bzrrCCIwo5CExYFUBlDy/dist=es2019,mode=imports/optimized/@tensorflow/tfjs-core.js:1977:18)
```

</details>

I don't mind making more PRs just to push this forward, but I really need help in pinning down the issue in tfjs.

**Comment by andykais** [comment]
that seems like its possibly a binding issue, it might be helpful to share a minimal repro code snippet @vicary. This looks like the source line https://github.com/tensorflow/tfjs/blob/master/tfjs-core/src/engine.ts#L424

**Comment by vicary** [comment]
@andykais Thanks for the hint. It turns out to be me prematurely disposing a tensor before the promise is resolved, we could definitely use a better error message but that's for another issue.

My Deno fork basically works for my use case.

**Comment by andykais** [comment]
tensorflow is not working with the current script in the latest version of deno. Running exactly the script described above:
```ts
import * as jpegts from "https://deno.land/x/jpegts@1.1/mod.ts";
;(window as any).document = {} // polyfill for browser detection
import * as tf from 'https://cdn.skypack.dev/@tensorflow/tfjs'
tf.env().set('IS_BROWSER', true)
import {PlatformBrowser} from 'https://cdn.skypack.dev/@tensorflow/tfjs-core/dist/platforms/platform_browser'
tf.env().setPlatform('browser', new PlatformBrowser());
import 'https://cdn.skypack.dev/@tensorflow/tfjs-backend-webgpu'
import * as poseDetection from 'https://cdn.skypack.dev/@tensorflow-models/pose-detection';


// initialize tensorflow
await tf.setBackend('webgpu')
await tf.ready()

console.log('isBrowser:', tf.device_util.isBrowser())
console.log('IS_BROWSER:', tf.env().getBool('IS_BROWSER'));

const detectorConfig = {
  modelType: poseDetection.movenet.modelType.MULTIPOSE_LIGHTNING,
}
const detector = await poseDetection.createDetector(poseDetection.SupportedModels.MoveNet, detectorConfig)

const file = await Deno.readFile('./sample.jpg')
const image = await jpegts.decode(file)
const poses = await detector.estimatePoses(image);
console.log(poses)
```

runs, but has an empty output of poses (`[]`)

Attempting to update the script to use npm specifiers looks like this:
```ts
import * as jpegts from "https://deno.land/x/jpegts@1.1/mod.ts";
;(window as any).document = {} // polyfill for browser detection
import * as tf from 'npm:@tensorflow/tfjs'
tf.env().set('IS_BROWSER', true)
import {PlatformBrowser} from 'npm:@tensorflow/tfjs-core/dist/platforms/platform_browser'
tf.env().setPlatform('browser', new PlatformBrowser());
import 'npm:@tensorflow/tfjs-backend-webgpu'
import * as poseDetection from 'npm:@tensorflow-models/pose-detection';


// initialize tensorflow
await tf.setBackend('webgpu')
await tf.ready()

console.log('isBrowser:', tf.device_util.isBrowser())
console.log('IS_BROWSER:', tf.env().getBool('IS_BROWSER'));

const detectorConfig = {
  modelType: poseDetection.movenet.modelType.MULTIPOSE_LIGHTNING,
}
const detector = await poseDetection.createDetector(poseDetection.SupportedModels.MoveNet, detectorConfig)

const file = await Deno.readFile('./sample.jpg')
const image = await jpegts.decode(file)
const poses = await detector.estimatePoses(image);
console.log(poses)
```

but this gives the following error:
```
error: Uncaught SyntaxError: Identifier 'mod' has already been declared
    at <anonymous> (file:///Users/andrew/Library/Caches/deno/npm/registry.npmjs.org/@tensorflow/tfjs/4.1.0/dist/tf.node.js:291:14)
```

I havent been able to discover the cause of that error, since it appears that the source line specified is not actually where the error is occurring

@google-ml-butler unstale
(if the google butler doesnt unstale this issue then I can just create a new one)

**Comment by andykais** [comment]
update, this is a minimally reproducable example that causes the SyntaxError:

```ts
import * as jpegts from "https://deno.land/x/jpegts@1.1/mod.ts";
;(window as any).document = {} // polyfill for browser detection
import * as tf from 'npm:@tensorflow/tfjs'
tf.env().set('IS_BROWSER', true)
```

deno --version output:
```
deno 1.28.3 (release, aarch64-apple-darwin)
v8 10.9.194.5
typescript 4.8.3```

**Comment by andykais** [comment]
Awesome, glad to hear this is an active issue. @haoyunfeix if you have the ability to reopen this issue could you do that?

**Comment by haoyunfeix** [comment]
As mentioned above, the empty output is caused by invalid shaders for naga.
I fixed all related shaders used by pose-detection in https://github.com/tensorflow/tfjs/compare/master...haoyunfeix:tfjs:fix_6746, as chrome implementation and naga are mutually exclusive, so we have to wait for https://github.com/gfx-rs/naga/issues/1829 to support `const` in naga side. Anyway, I finally got the same result as the CPU backend on the WebGPU backend.

I attached the sample code and rebuilt webgpu js file, please try as you like. You can also try with fix_6746 branch to build a local package for yourself.

[latest.zip](https://github.com/tensorflow/tfjs/files/10252722/latest.zip)

**Comment by haoyunfeix** [comment]
@andykais shader problems fixed with #7193, please look forward to the next version(should be https://cdn.skypack.dev/@tensorflow/tfjs-backend-webgpu@0.0.1-alpha.17, not published yet) can be runnable on your demo.

**Comment by andykais** [comment]
just sharing back the working code with the most recent fix:

```ts
import * as jpegts from "https://deno.land/x/jpegts@1.1/mod.ts";
;(window as any).document = {} // polyfill for browser detection
import * as tf from 'https://cdn.skypack.dev/@tensorflow/tfjs'
import 'https://cdn.skypack.dev/@tensorflow/tfjs-backend-webgpu@0.0.1-alpha.17'
tf.env().set('IS_BROWSER', true)
import {PlatformBrowser} from 'https://cdn.skypack.dev/@tensorflow/tfjs-core/dist/platforms/platform_browser'
tf.env().setPlatform('browser', new PlatformBrowser());
import * as poseDetection from 'npm:@tensorflow-models/pose-detection';

// initialize tensorflow
await tf.setBackend('webgpu')
await tf.ready()

tf.env().set('WEBGPU_DEFERRED_SUBMIT_BATCH_SIZE', 1);
// console.log('isBrowser:', tf.device_util.isBrowser())
// console.log('IS_BROWSER:', tf.env().getBool('IS_BROWSER'));
// console.log(tf.getBackend());

const detectorConfig = {
  modelType: poseDetection.movenet.modelType.MULTIPOSE_LIGHTNING,
}
const detector = await poseDetection.createDetector(poseDetection.SupportedModels.MoveNet, detectorConfig)

const file = await Deno.readFile('./sample.jpg')
const image = await jpegts.decode(file)
const poses = await detector.estimatePoses(image);

console.log(poses)
```

I am still not able to use npm specifiers for really any of these modules, I assume thats because not all the relevant pieces have been published (though the problematic webgpu backend code _has_ been published on npm https://www.npmjs.com/package/@tensorflow/tfjs-backend-webgpu/v/0.0.1-alpha.17)

**Comment by haoyunfeix** [comment]
@andykais Thanks for the feedback!

Your pasted code works on my machine, env:
__deno 1.28.3 (release, x86_64-pc-windows-msvc), v8 10.9.194.5, typescript 4.8.3,__ 
could you share more about what problems you met?

And did you try to reload your cache? => `deno cache --reload mod.ts`

**Comment by haoyunfeix** [comment]
Deno latest version 1.30.3 hits an error when loading webgpu backend, refs to https://github.com/denoland/deno/issues/17869

**Comment by andykais** [comment]
the script I have above works on deno latest version 1.31.1 (the webgpu backend issue was solved in the deno repo). However, I still cannot use npm specifiers, only skypack imports. A very tiny repro looks like this:
```ts
;(window as any).document = {} // polyfill for browser detection
import * as tf from 'npm:@tensorflow/tfjs@4.2.0'
tf.env().set('IS_BROWSER', true)
```
`deno run -A --unstable --check github-issue-repro.ts`
```
error: Uncaught SyntaxError: Identifier 'mod' has already been declared
    at <anonymous> (file:///Users/andrew/Library/Caches/deno/npm/registry.npmjs.org/@tensorflow/tfjs/4.2.0/dist/tf.node.js:233:14)
```

**Comment by mzygmunt** [comment]
> the script I have above works on deno latest version 1.31.1 (the webgpu backend issue was solved in the deno repo). However, I still cannot use npm specifiers, only skypack imports. A very tiny repro looks like this:
> 
> ```ts
> ;(window as any).document = {} // polyfill for browser detection
> import * as tf from 'npm:@tensorflow/tfjs@4.2.0'
> tf.env().set('IS_BROWSER', true)
> ```
> 
> `deno run -A --unstable --check github-issue-repro.ts`
> 
> ```
> error: Uncaught SyntaxError: Identifier 'mod' has already been declared
>     at <anonymous> (file:///Users/andrew/Library/Caches/deno/npm/registry.npmjs.org/@tensorflow/tfjs/4.2.0/dist/tf.node.js:233:14)
> ```

I've the same. @andykais  Did you find any solution?
